spring.application.name=course-service

# Server Config
server.port=8002

# MySQL JDBC Config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/itbook_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:app_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:app_password}

# Hibernate (JPA) Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Eureka Config
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false