spring.application.name=frontend-service

# Server Config
server.port=8000

# Static Resources
spring.web.resources.static-locations=classpath:/static/

# Eureka Config
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false