spring.application.name=chat-service

# Server Config
server.port=8003

# MySQL JDBC Config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/itbook_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:app_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:app_password}

# JPA Config
spring.jpa.hibernate.ddl-auto=update

# Eureka Config
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false